import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/Footer";
 // _app.tsx or layout.ts

import 'leaflet/dist/leaflet.css';

import { Providers } from "./providers";
import LoadingOverlay from "./components/RouteLoader";
import { ThemeProvider } from "next-themes";
import Navbar from "./components/Navbar";
export const metadata: Metadata = {
  title: "Proofly.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
          {/*local pg script */}
            <script src="https://proofly-delta.vercel.app" data-user-id="5e6bcd29-77c8-4dbe-a28b-1c8986fc8694" data-site-id="39b858b9-f2fe-4cfd-b34b-e4b6a2a7e389"></script>     
           {/* <script src="https://proofly-delta.vercel.app/api/Tracker" data-user-id="5e6bcd29-77c8-4dbe-a28b-1c8986fc8694" data-site-id="39b858b9-f2fe-4cfd-b34b-e4b6a2a7e389"></script>     */}
      </head>
      <body>
        
       <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <Providers>
          <Navbar/>
          <LoadingOverlay/>
          <div className="pt-20">
        {children}
        </div>
        <Footer/>
        </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
